<a href="https://colab.research.google.com/github/BigDaa007/Machine-Learning-Notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # **Numpy Basics**

 ## **Import Numpy**

In [2]:
import numpy as np


 ## **Create Numpy array**

In [ ]:
a= np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
 b = np.array([[1],[2],[3],[4],[5]])
 print(b)
 print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [ ]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


 ## **Create Zeros , Ones , Custom Array**

In [ ]:
a = np.zeros((3,3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b = np.ones((2,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Array of some constants

c = np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


 ## **Identity Matrix - Size/Square Matrix**

In [ ]:
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


 ## **Random Matrix**

 np.random.random
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.

In [ ]:
randomMatrix = np.random.random()
print(randomMatrix)

0.12832737715546894


In [ ]:
randomMatrix1 = np.random.random((2,3))
print(randomMatrix1)

[[0.4042233  0.62758539 0.5339087 ]
 [0.2340853  0.95590479 0.63151716]]


In [ ]:
print(randomMatrix1[:,1])

[0.62758539 0.95590479]


 ## **Set some rows and columns with any value**

In [ ]:
e = np.zeros((3,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
e[1,:]=5
print(e)

[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]


In [ ]:
e[:,-1]=7
print(e)

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


 ## **DataTypes**

In [ ]:
print(e.dtype)


float64


In [ ]:
e = np.zeros((3,3),dtype=np.int64)
print(e)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
print(e.dtype)

int64


 # **Mathematical Operations**

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


 ## **Element wise addition**

In [ ]:
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


 ## **Element wise subtraction**

In [ ]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


 ## **Element wise Multiply**

In [ ]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


 ## **Element wise Divide**

In [ ]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


 ## **Square Root**

In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


 ## **Matrix Multiplication / Dot Products**

In [ ]:
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


 ## **Multiplication Of Vectors**

In [ ]:
# Multiplication of two vectors is a scalar
f = np.array([1,2,3,4,5])
g = np.array([4,5,6,7,8])
print(f.dot(g))

100


 ## **Sum**

In [ ]:
print(f)
print(sum(f))

[1 2 3 4 5]
15


In [ ]:
print(x)
print(np.sum(x))

[[1 2]
 [3 4]]
10


In [ ]:
# Column Wise Sum
print(np.sum(x,axis = 0))   

# Row Wise sum
print(np.sum(x,axis = 1))    

[4 6]
[3 7]


 # **Some More Numpy Functions**

*   min,max
*   mean
*   median
*   average
*   variance
*   stantard deviation



 ## **Min,Max**

In [5]:
h = np.array([[1,2,3,4],[7,6,2,0]])
print(h)
print(np.min(h))
print(np.min(h,axis=0))
print(np.min(h,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [6]:
print(np.max(h))
print(np.max(h,axis=0))
print(np.max(h,axis=1))

7
[7 6 3 4]
[4 7]


 ## **Mean**

In [11]:
i = np.array([1,2,3,4,5])
m = sum(i)/5
print(m)

print(np.mean(i))
print(np.mean(h,axis=0))
print(np.mean(h,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


 ## **Median**

In [12]:
print(np.median(i))

3.0


 ## **Mean vs Average**

In [14]:
# Average is weghted
print(np.mean(i))
w= np.array([1,3,5,6,7])
wi = [1,1,1,1,1]
print(np.average(i,weights=w))
print(np.average(i,weights=wi))
# If weights = 1 then Average = Mean

3.0
3.6818181818181817
3.0


 ## **Standard Deviation**

In [16]:
u=np.mean(i)
myStd = np.sqrt(np.mean(abs(i-u)**2))
print(myStd)

# Inbuilt Function
dev = np.std(i)
print(dev)

1.4142135623730951
1.4142135623730951


 ## **Variance**

In [17]:
print(myStd**2)
print(np.var(i))

2.0000000000000004
2.0


# **Numpy Random Module**

*    rand   : Random Values in a given shape
*    randn  : Returns a sample (or samples) from the "standard normal" distribution
*    randint: Returns random integers from low(inclusive) to high(exclusive)
*    random : Return random floats in the half-open interval [0.0 , 1.0)
*    choice : Generated a random sample from a given 1-D array
*    shuffle: Shuffles the contents of a sequence
*    seed   : fix the randomness

In [18]:
j = np.arange(1,10,2)
print(j)

[1 3 5 7 9]


In [28]:
j = np.arange(1,10,2) +10
print(j)

[11 13 15 17 19]


In [19]:
np.random.shuffle(j)
print(j)

[9 3 1 7 5]


In [24]:
np.random.choice(j)

5

In [25]:
k  = np.random.randn(2,3)
print(k)

[[-0.17504648 -0.91467276 -0.78591223]
 [ 1.24744937  0.65332065  1.7319675 ]]


In [26]:
np.random.randn()

-1.3291991090967314

In [27]:
np.random.randint(10,100,5)

array([20, 54, 94, 48, 27])

In [38]:
np.random.seed(1)
np.random.randint(10,100,5)

array([47, 22, 82, 19, 85])